import Nav from "@/components/Nav";
import CartDrawer from "@/components/CartDrawer";
import { CartProvider } from "@/components/CartContext";
import BackgroundDots from "@/components/BackgroundBalls";


import "./globals.css";

// Component to render background balls

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-[#8B4513]">
        <CartProvider>
          {/* Floating balls background */}
          {/* <BackgroundDots /> */}

          <Nav className="mb-4 text-white z-20 " />
          <CartDrawer />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
