import RootLayoutClientWrapper from "./RootLayoutClientWrapper";

import "./globals.css";

// Component to render background balls

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-white">
          {/* Floating balls background */}
          {/* <BackgroundDots /> */}
          <RootLayoutClientWrapper>{children}</RootLayoutClientWrapper>

      </body>
    </html>
  );
}
